"""
CalculiX .inp writer and ccx subprocess runner.

Provides write_inp() to assemble a full analysis input file from mesh,
loads, boundary conditions, and material cards, and run_simulation() to
shell out to the ccx CLI and return paths to the .frd and .dat results.
Raises SimulationError if ccx exits non-zero.

Multi-bracket-type support: pass a BracketType to write_inp() to select
the fixed-face and tip-node detection functions. Defaults to L-bracket.
"""

import logging
import math
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)


class SimulationError(Exception):
    """Raised when CalculiX simulation fails."""


def _parse_mesh_inp(mesh_path: Path) -> tuple[dict, list, list]:
    """
    Parse a Gmsh-written mesh.inp and return:
      nodes                : dict {node_id: (x, y, z)}
      element_header_lines : list of *ELEMENT header strings
      element_lines        : list of raw element data lines (strings)

    Handles multiple *NODE and *ELEMENT sections.
    """
    nodes: dict[int, tuple[float, float, float]] = {}
    element_lines: list[str] = []
    element_header_lines: list[str] = []

    in_node = False
    in_element = False

    with mesh_path.open(encoding="utf-8") as fh:
        for line in fh:
            stripped = line.strip()
            upper = stripped.upper()

            if upper.startswith("*NODE") and not upper.startswith("*NODE PRINT"):
                in_node = True
                in_element = False
                continue

            if upper.startswith("*ELEMENT"):
                in_element = True
                in_node = False
                element_header_lines.append(stripped)
                continue

            if stripped.startswith("*"):
                in_node = False
                in_element = False
                continue

            if in_node and stripped:
                parts = stripped.split(",")
                if len(parts) >= 4:
                    try:
                        nid = int(parts[0].strip())
                        x = float(parts[1].strip())
                        y = float(parts[2].strip())
                        z = float(parts[3].strip())
                        nodes[nid] = (x, y, z)
                    except ValueError:
                        pass

            if in_element and stripped:
                element_lines.append(stripped)

    return nodes, element_header_lines, element_lines


def write_inp(
    mesh_path: Path,
    loads: dict,
    bcs: dict,
    material: dict,
    output_dir: Path,
    bracket_type=None,
) -> Path:
    """
    Assemble a full CalculiX analysis.inp from mesh + cards.

    Parameters
    ----------
    mesh_path    : Path — mesh.inp from Gmsh
    loads        : dict — {type, magnitude_n, direction}
    bcs          : dict — {type: "fixed_face"}; bcs["params"] holds geo params
    material     : dict — {E_pa, nu, rho, Sy_pa}
    output_dir   : Path
    bracket_type : BracketType | None — selects fixed_nodes_fn / tip_node_fn.
                   Defaults to L-bracket when None.

    Returns
    -------
    Path to analysis.inp
    """
    if bracket_type is None:
        from bracket_types import get_type
        bracket_type = get_type("l_bracket")

    mesh_path  = Path(mesh_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Parse mesh
    logger.info("Parsing mesh: %s", mesh_path)
    nodes, elem_headers, elem_lines = _parse_mesh_inp(mesh_path)
    if not nodes:
        raise SimulationError(f"No nodes parsed from {mesh_path}")

    # 2. Get geometry params from bcs dict
    params = bcs.get("params", {})

    # 3. Identify FIXED node set via bracket_type
    fixed_nodes = bracket_type.fixed_nodes_fn(nodes, params)
    if not fixed_nodes:
        raise SimulationError(
            f"No fixed nodes found for {bracket_type.name} "
            f"(via {bracket_type.fixed_nodes_fn.__name__}). "
            "Check that the mesh covers the geometry's fixed face."
        )
    logger.debug("Fixed nodes (%s): %d", bracket_type.name, len(fixed_nodes))

    # 4. Identify TIP node via bracket_type
    tip_node = bracket_type.tip_node_fn(nodes, params)
    logger.debug("Tip node %d at %s", tip_node, nodes[tip_node])

    # 5. Determine load DOF and sign
    direction = loads.get("direction", "-Z").upper().strip()
    magnitude = float(loads.get("magnitude_n", 0.0))
    dof_map = {"X": 1, "Y": 2, "Z": 3, "-X": 1, "-Y": 2, "-Z": 3}
    load_dof = dof_map.get(direction, 3)
    load_sign = -1.0 if direction.startswith("-") else 1.0
    load_value = load_sign * magnitude

    E_pa  = material["E_pa"]
    nu    = material["nu"]
    rho   = material["rho"]

    # 6. Read raw mesh.inp for node/element blocks
    raw_mesh = mesh_path.read_text(encoding="utf-8")

    # 7. Assemble analysis.inp
    out_path = output_dir / "analysis.inp"
    lines = []

    lines.append("** CalculiX analysis generated by bracket-agent")
    lines.append("**")

    # Re-emit *NODE block
    lines.append("*NODE, NSET=NALL")
    for nid in sorted(nodes.keys()):
        x, y, z = nodes[nid]
        lines.append(f"{nid}, {x:.10e}, {y:.10e}, {z:.10e}")

    # Re-emit *ELEMENT blocks — only 3D solid elements (C3D*) go into EALL
    in_elem = False
    for raw_line in raw_mesh.splitlines():
        stripped = raw_line.strip()
        upper = stripped.upper()
        if upper.startswith("*ELEMENT"):
            parts = [p.strip() for p in stripped.split(",")]
            type_part = next((p for p in parts if p.upper().startswith("TYPE")), "")
            elem_type = type_part.split("=")[-1].strip().upper()
            if elem_type.startswith("C3D"):
                parts = [p for p in parts if not p.upper().startswith("ELSET")]
                parts.append("ELSET=EALL")
                lines.append(", ".join(parts))
                in_elem = True
            else:
                in_elem = False
            continue
        if stripped.startswith("*"):
            in_elem = False
            continue
        if in_elem and stripped:
            lines.append(stripped)

    # --- Node sets ---
    lines.append("*NSET, NSET=NALL, GENERATE")
    nids_sorted = sorted(nodes.keys())
    lines.append(f"{nids_sorted[0]}, {nids_sorted[-1]}, 1")

    lines.append("*NSET, NSET=FIXED")
    for i in range(0, len(fixed_nodes), 16):
        chunk = fixed_nodes[i:i + 16]
        lines.append(", ".join(str(n) for n in chunk))

    lines.append("*NSET, NSET=TIP")
    lines.append(str(tip_node))

    # --- Material ---
    lines.append("*MATERIAL, NAME=STEEL")
    lines.append("*ELASTIC")
    lines.append(f"{E_pa:.6e}, {nu:.4f}")
    lines.append("*DENSITY")
    lines.append(f"{rho:.4f}")
    lines.append("*SOLID SECTION, ELSET=EALL, MATERIAL=STEEL")

    # --- Step ---
    lines.append("*STEP")
    lines.append("*STATIC")

    lines.append("*BOUNDARY")
    lines.append("FIXED, 1, 6")

    lines.append("*CLOAD")
    lines.append(f"TIP, {load_dof}, {load_value:.6e}")

    lines.append("*NODE PRINT, NSET=NALL")
    lines.append("U")
    lines.append("*EL PRINT, ELSET=EALL")
    lines.append("S")
    lines.append("*NODE FILE")
    lines.append("U")
    lines.append("*EL FILE")
    lines.append("S")

    lines.append("*END STEP")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Analysis .inp written: %s", out_path)
    return out_path


def run_simulation(inp_path: Path) -> tuple[Path, Path]:
    """
    Run CalculiX on inp_path and return (frd_path, dat_path).

    Raises SimulationError on ccx failure or missing output files.
    """
    inp_path   = Path(inp_path)
    output_dir = inp_path.parent
    stem       = inp_path.stem

    logger.info("Running ccx: %s", inp_path)
    try:
        result = subprocess.run(
            ["ccx", "-i", stem],
            cwd=str(output_dir),
            capture_output=True,
            text=True,
            timeout=600,
        )
    except FileNotFoundError as exc:
        raise SimulationError("ccx not found on PATH") from exc
    except subprocess.TimeoutExpired as exc:
        raise SimulationError("ccx timed out after 600 s") from exc

    if result.returncode != 0:
        raise SimulationError(
            f"ccx exited {result.returncode}\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )

    frd_path = output_dir / f"{stem}.frd"
    dat_path = output_dir / f"{stem}.dat"

    if not frd_path.exists():
        raise SimulationError(
            f"{frd_path.name} not produced by ccx.\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    if not dat_path.exists():
        raise SimulationError(
            f"{dat_path.name} not produced by ccx.\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )

    logger.info("Simulation complete: %s, %s", frd_path, dat_path)
    return frd_path, dat_path
